dist: xenial
language: java
jdk:
  - openjdk8
before_install:
  - rm ~/.m2/settings.xml || true
  - ulimit -c unlimited -S
script:
  # TODO: Remove need to skip tests...
  - ./mvnw package -Dmaven.test.skip
cache:
  directories:
    - $HOME/.m2
env:
  global:
    - JAVA_OPTS: "'-Xms1g -Xmx2g'"